import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import { Geist, Geist_Mono, Bricolage_Grotesque } from "next/font/google";
import GlobalNavigation from "@/component/GlobalNavigation";
import Footer from "@/component/Footer";
import "@radix-ui/themes/styles.css";
import "./globals.css";


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const bricolage = Bricolage_Grotesque({
	variable: "--font-bricolage-grotesque",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${bricolage.variable}`}>
			<body className="antialiased min-h-screen flex flex-col">
				<Theme>
					<GlobalNavigation />
					<main>
						{children}
					</main>
					<Footer />
				</Theme>
			</body>
		</html>
	);
}
