import type {Metadata} from "next";
import {Theme} from "@radix-ui/themes";
import {Bricolage_Grotesque, Geist, Geist_Mono} from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import React from "react";
import NavBar from "@/components/NavBar";

// Display font - used for headings and titles
const bricolageGrotesque = Bricolage_Grotesque({
	variable: "--font-display",
	subsets: ["latin"],
	display: "swap",
});

// Sans/body font - used for body text
const geistSans = Geist({
	variable: "--font-sans",
	subsets: ["latin"],
	display: "swap",
});

// Mono font - used for code
const geistMono = Geist_Mono({
	variable: "--font-mono",
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	                                   children,
                                   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${bricolageGrotesque.variable} ${geistSans.variable} ${geistMono.variable}`}
		>
		<body className={"antialiased"}>
		<Theme>
			<NavBar className="sticky top-0 z-50 bg-surface" />
			<main>{children}</main>
		</Theme>
		</body>
		</html>
	);
}
